create table accounts (
id int generated by default as identity,
name varchar(100) not null,
balance dec(15,2) not null, 
primary key(id)
);

INSERT INTO accounts(name, balance) VALUES ('user1', 10000), ('user2', 8000), ('user3', 9000);
insert into accounts(name, balance) values ('user4', 1000);

select * from accounts;

create or replace procedure transfer(
sender int,
receiver int,
amount dec
)
language plpgsql as $$
declare
sender_balance dec;
begin
if sender = receiver then
raise exception 'Sender and receiver cannot be the same';
end if;

select balance into sender_balance from accounts
where id=sender;
if sender_balance is null then
raise exception 'Sender does not exist';
end if;
if sender_balance < amount then
raise exception 'Insufficient balance';
end if;

if not exists (select 1 from accounts where id = receiver) then
raise exception 'Receiver does not exist';
end if;

update accounts
set balance = balance - amount
where id = sender;

update accounts
set balance = balance + amount
where id = receiver;

commit;
end;
$$;



call transfer(8,1,1000);